name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14.19.0', '16.14.0', '17.4.0']
    name: Node ${{ matrix.node }} testing
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - name: eslint
        run: npm run lint:check
      - name: prettier
        run: npm run format:check
      - name: ts-compile-check
        run: npm run ts-compile-check
      - name: test
        run: npm test
        env:
          CI: true
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .nyc_output
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17.4.0'
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: coverage
          path: .nyc_output
      - name: coverage
        run: |
          npm i -g coveralls
          npx nyc check-coverage --lines 85 --per-file
          npx nyc report > lcov.info
          coveralls < lcov.info
        env:
          CI: true
          COVERALLS_REPO_TOKEN: ${{ secrets. COVERALLS_REPO_TOKEN }}
  release:
    if: github.ref == 'refs/heads/master'
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17.4.0'
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
